platform :ios, '11.0'

target 'FirebaseStarterKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseStarterKit

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/AdMob'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

end
